version: "2"
services:
  ldap:
    image: marcgc/ldapserver19:latest
    container_name: ldapserver
    hostname: ldapserver
    ports: 
      - "389:389"
    networks:
     - ldapnet
    privileged: true
  samba:
    image: marcgc/samba19:pam
    container_name: samba
    hostname: samba
    volumes:
      - "homes:/tmp/home"
    ports:
      - "139:139"
      - "445:445"
    networks:
     - ldapnet
    privileged: true
#  nfs:
#    image: marcgc/nfs19:pam
#    container_name: nfs
#    hostname: nfs
#    volumes:
#      - "homes:/tmp/home"
#        #    ports:
#        #- "111:111"
#        #- "2049:2049"
#    privileged: true
#    networks:
#     - ldapnet
  pam:
    image: marcgc/hostpam19:samba
    container_name: pam
    hostname: pam
    networks:
     - ldapnet
    privileged: true
networks:
  ldapnet:
volumes:
  homes:
